seed: 42
device: cuda
dataset:
  root: ""
  dt: 0.00833
  resolution: [180, 320] #这个大小是fno保留的尺寸，不是原始输入尺寸
  sample_stride: 4 #采样步长，即每隔多少个时间步采样一个窗口
  windowing_mode: imu #画窗方式
  window_dt: 0.00833 #每个窗口的时间长度
  train_split: 0.9
model:
  window_stack_K: 3 #窗口栈深度，即每个窗口的时间长度
  voxel_stack_mode: delta
  scale_min: 0.0
  scale_max: 1.0
training:
  epochs: 500
  batch_size: 512
  lr: 0.001
  eval_interval: 1
  eval_batch_size: 1
  tbptt_len: 75
  num_workers: 2
  sequence_len: 400 #每个批次的序列长度
  sequence_stride: 400 #序列步长，即每隔多少个时间步采样一个序列
  persistent_workers: true
  prefetch_factor: 1
  mixed_precision: true
  scheduler: cosine
  warmup_epochs: 10
  patience: 50
  earlystop_metric: ate
  optimizer: adamw
  weight_decay: 0.01
