seed: 42
device: cuda
dataset:
  root: ""
  dt: 0.00833
  resolution: [180, 320]
  sample_stride: 4
  windowing_mode: imu
  window_dt: 0.00833
  train_split: 0.0  # 使用完整数据集进行评估
model:
  window_stack_K: 3
  voxel_stack_mode: delta
  scale_min: 0.0
  scale_max: 1.0
training:
  epochs: 500
  batch_size: 512
  lr: 0.00006
  eval_interval: 1
  eval_batch_size: 1
  tbptt_len: 75
  num_workers: 2
  sequence_len: 400
  sequence_stride: 400
  persistent_workers: true
  prefetch_factor: 1
  mixed_precision: true
  scheduler: cosine
  warmup_epochs: 20
  patience: 50
  earlystop_metric: ate
  optimizer: adamw
  weight_decay: 0.01
